apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-service-example
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-con
        image: nginx
        ports:
        - containerPort: 80
