apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-deploy1
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gameoflife
  targetCPUUtilizationPercentage: 50
status:
  currentReplicas: 3
  desiredReplicas: 0
